### ISSUE TITLE
OMSagent as a daemonset on Kubernetes cluster

### ISSUE THREAD

**Issue by cricketfan5** [Microsoft/OMS-docker#123]
When we deploy a OMSagent as a daemonset it should turn green in the security center showing as VM is monitored by the OMSagent. And we are deploying OMSagent on a Kubernetes cluster with COREOS VM.
we are provisioning the vm with omsagent as extension and as extension doesn't work on coreos vm. we are deploying agent as a daemonset.
When we are having the extension and deploying the daemonset it is turning green in the security center.
We decided to disable the extension as extension doesn't work on COREOS and we deployed the agent as a daemonset. But is not turning into green. I don't see any difference between the VM's other than the extension enabled on one vm and disabled on the other.
I don't understand what is the relation between the extension and daemonset. Can anyone here help me understand as I don't see any log why it is not turning into green?. Any help is appreciated. Thanks!

**Comment by keikhara** [comment]
@cricketfan5 This agent is only focused to do container monitoring. For security, we will let you know who the contacts will be. At this moment, omsagent which security team uses does not support CoreOS. 
Please see support matrix - https://github.com/Microsoft/OMS-Agent-for-Linux#supported-linux-operating-systems

**Comment by cricketfan5** [comment]
@keikhara Yes, it does not support CoreOS. So, I am installing it as a daemonset. when we install it as a daemonset does that turn green in the security center?. Thanks

**Comment by cricketfan5** [comment]
@keikhara when we install omsagent as a deamonset does it shows VM is now connected to Log analytics or we have to manually connect vm to Log Analytics.

**Comment by keikhara** [comment]
@cricketfan5 I responded to you on the other issues. This due to the containerized agent disabling dsc. This is not an error.
