### ISSUE TITLE
Configuring what to log in AKS

### ISSUE THREAD

**Issue by seniorquico** [microsoft/OMS-docker#172]
I followed the installation guide (link below) to get Log Analytics working in a AKS instance using the Azure Portal (the automated, GUI approach).

https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-onboard

Everything appears to be working. However, I'd like to configure _what_ gets logged. Currently, all of our containers' stdout/stderr is being forwarded to the workspace. We have a few services that are _very_ chatty, for no good reason, and can't be adjusted.

Is it possible to configure the agent to _not_ log stdout but continue to log stderr for specific container instances? If not, is it possible to configure the agent to _not_ log anything for specific container instances?

**Comment by vishiy** [comment]
@seniorquico we have this in the backlog. we plan to get to this sometime this summer.

**Comment by florianrusch** [comment]
@vishiy any progress so far? We also need this feature...our cluster creates more logs than our applications :see_no_evil: 

It would also be nice if we could configure this at the creation of a new cluster via the Azure Portal or for example with Terraform (Azure API / CLI). To you plan to support this case?

**Comment by vishiy** [comment]
@florianrusch - This is in the works now.
Below is what we are thinking -
1) Being able to turn OFF/ON stdout/stderr logs globally (for all containers in all nodes in the cluster)
2) Being able to turn OFF/ON stdout logs globally
3) Being able to turn OFF/ON stderr logs globally
4) Provide a namespace 'exclusion' list to exclude certain namespaces for stdout (will be effective only if stderr log collection is enabled)
5) Provide a namespace 'exclusion' list to exclude certain namespaces for stderr (will be effective only if stderr log collection is enabled)

would that be helpful for your scenarios ?

We are in design phase now and will soon start implementing. Dont have a release ETA yest for this.

**Comment by florianrusch** [comment]
The configuration on container level would be nice, but we are looking to disable the meta/control plane logs from kubernetes itself. I'm not sure, if this is the right place to ask about this. 🙈 If this is the wrong place pls let me know!

In the Azure Log Analytics Workspace we have a bunch of Insights and Logs which we doesn't need. For example `KubeNodeInventory`, `KubeEvents`, `KubeServices` etc. We would like to deactivate the collection/scraping process of these.

**Comment by dhirschfeld** [comment]
> This is in the works now

Just curious if this capability ever got implemented? Or if not, what the current status is?

**Comment by vishiy** [comment]
This was released quite some time back. Please refer to our documentation. 

https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-agent-config
