### ISSUE TITLE
OMS Agent will not pick up the new Docker CE and DC editions with new versions

### ISSUE THREAD

**Issue by dansand71** [Microsoft/OMS-docker#18]
Last week Docker released new versions of their engine.  When this new version 1.17* is installed however the OMS agent does not recognize that version and exits...

**Comment by dwaiba** [comment]
It does receive the new versions... Details here -> https://github.com/Azure/azure-docker4azureoms

**Comment by keikhara** [comment]
Hi @dansand71, we will get back you on this. We have a checker within our script which needs to support the latest version change on docker.

**Comment by keikhara** [comment]
@dansand71  We will provide a new fix asap. We will keep you posted. thanks,

**Comment by keikhara** [comment]
@dansand71 can you try microsoft/oms:test image? This hot fix should eliminate the issue. 
thanks,

**Comment by keikhara** [comment]
@dansand71  this is now fixed.
