### ISSUE TITLE
Release new image for 1.3.1-15a

### ISSUE THREAD

**Issue by edevil** [Microsoft/OMS-docker#21]
I've noticed that there are already placeholders for the 1.3.1-15a release, but the Dockerfile still references an older version.

**Comment by edevil** [comment]
The "latest" microsoft/oms image already has ruby 2.3.3, so I guess it is the latest version, but there's no tag.

**Comment by keikhara** [comment]
@edevil  1.3.1-15a is not official. Please do not use that version. We will have a new one call 1.3.2-15. We will provide by today.
