### ISSUE TITLE
Instructions for docker swarm

### ISSUE THREAD

**Issue by andrefernandes** [Microsoft/OMS-docker#27]
I used the command on a swarm manager create with Docker for Azure template:

    swarm-exec  docker run --privileged -d -v /var/run/docker.sock:/var/run/docker.sock -e WSID="MY_ID" -e KEY="MY_KEY" -h=`hostname` -p 127.0.0.1:25225:25225 --restart=always microsoft/oms

Seems to work fine (all nodes show up on OMS portal). If it is correct could you please add this the the docs?

**Comment by keikhara** [comment]
@andrefernandes I will add a docker swarm instructions. Will keep you noticed. 
It should be 

docker service create  --name omsagent --mode global  --mount type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock  -e WSID="<WORKSPACE ID>" -e KEY="<PRIMARY KEY>" -p 25225:25225 -p 25224:25224/udp  --restart-condition=on-failure microsoft/oms

we will have docker compose file soon.

**Comment by keikhara** [comment]
@andrefernandes Added to the dockerswarm folder. Please go there. 
Thanks.
