### ISSUE TITLE
OMS agent kubernetes daemonset is not collecting host journald logs

### ISSUE THREAD

**Issue by edevil** [Microsoft/OMS-docker#29]
I setup the daemonset as per the [instructions](https://github.com/Microsoft/OMS-docker/blob/master/Kubernetes/omsagent.yaml) but the daemon is not collecting the kubernetes' hosts journald logs. Is there a way to collect these as well?

**Comment by jauco** [comment]
is it collecting the logs of the other containers?

**Comment by keikhara** [comment]
@edevil 
we are aware of this. We have a new bits which should be out next week. We will keep you informed when it is out. Meanwhile, if you like to test it, it is microsoft/oms:leaf. 

regards,

**Comment by edevil** [comment]
@jauco yes, it collects logs of containers

@keilhara great news. Will these "new bits" also include fetching kubernetes metadata such as namespace name and pod name? :)

**Comment by keikhara** [comment]
@edevil  Not yet. This new bits are part the latest tag now and they are mainly bug fix. Release note is updated.

**Comment by keikhara** [comment]
closing. It will be in next release.
