### ISSUE TITLE
[Feature Request] Ability to Pass Bearer Token for Cluster Metric Collection

### ISSUE THREAD

**Issue by AnthonyHerman** [microsoft/OMS-docker#365]
Hi there, 

I'm following https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-prometheus-integration in order to scrape metrics from a Kubernetes service. The configmap and guide are great however I'm not able to actually retrieve metrics because the metrics endpoint requires a bearer token. With prometheus this is normally accomplished with the `bearer_token` or `bearer_token_file` variables however this does not seem possible here.

I'm using this configmap template:
https://github.com/microsoft/OMS-docker/blob/ci_feature_prod/Kubernetes/container-azm-ms-agentconfig.yaml

Please let me know if this should actually go somewhere else.

Thanks!

**Comment by vishiy** [comment]
We scrape using bearer token and TLS cert. So everything should just work out of the box, and you should just be providing the scrape endpoint URL.
