### ISSUE TITLE
Docker container logs stop reporting with OMS agent

### ISSUE THREAD

**Issue by kevinlisota** [Microsoft/OMS-docker#43]
I have two VM's and 4 docker containers being monitored by OMS using the OMS agent for Linux.

When I start a container, it sends containerlog data to OMS for about a day or so and then stops sending it, or at least nothing is being collected in the OMS portal

The containers are still running fine and the VM hosts continue to report their stats to OMS.

Restarting the containers restarts the container log collection, but eventually it stops.

How can I troubleshoot/fix this issue?

**Comment by keikhara** [comment]
@kevinlisota which version of the OMS Agent are you using? We have done some fixes for the container logs.

**Comment by kevinlisota** [comment]
Both of my VM hosts are running 1.35-127 of the OMS agent for Linux. VM host data is being collected. So is container inventories. 

It is just the container logs themselves that will stop after about a day of collection.

**Comment by keikhara** [comment]
@kevinlisota Is this agent on the host rather than the containerzied linux agent? Is that is the case, we will be adding the fix to the linux agent by the end of this month.

**Comment by kevinlisota** [comment]
Correct, the agent is on the host. It is not containerized. I'll watch for this fix

**Comment by keikhara** [comment]
@kevinlisota  we are looking to add the fix in the next release which is slated in few days. Will keep you posted.

**Comment by keikhara** [comment]
@kevinlisota new release of the oms agent is out. 1.4.0-12 version. 
Please try this and let us know whether this works. This should have the fix. 
https://github.com/Microsoft/OMS-Agent-for-Linux/releases

**Comment by kevinlisota** [comment]
Thanks @keikhara. This update seems to have fixed it.
