### ISSUE TITLE
How to setup HTTP proxy server setting for OMS docker container

### ISSUE THREAD

**Issue by phagunbaya** [Microsoft/OMS-docker#54]
I'm using kubernetes cluster and deploying omsagent as daemonset. How do I configure HTTP proxy server setting for oms container to use ?

https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/OMS-Agent-for-Linux.md#configuring-the-agent-for-use-with-an-http-proxy-server

**Comment by keikhara** [comment]
Not supported at this moment.

**Comment by tobiaskohlbau** [comment]
Why it's not supported? Is there a reason for not implementing this?
