### ISSUE TITLE
Please provide examples for Windows Containers

### ISSUE THREAD

**Issue by artisticcheese** [Microsoft/OMS-docker#64]
Need more examples about deploying and utilizing containers with OMS on Windows.
I have Windows swarm running with Windows containers. It's 100% Microsoft+docker environment. Not even scent of Linux. And here we are asking Microsoft to provide documentation how to support their oldest baby.

**Comment by keikhara** [comment]
We don't have a containerized agent for Windows Agent. 
For Windows, you will need to install the Agent on each host. 
Here's the doc for this. https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-containers#windows-container-hosts
