### ISSUE TITLE
Error response in Docker swarm in Azure container Service

### ISSUE THREAD

**Issue by anushkaee** [Microsoft/OMS-docker#67]
Hi, 
when i try to run OMS agent in Azure Container Service swarm cluster  master node.
command: docker service create  --name omsagent --mode global  --mount type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock  -e WSID="myid" -e KEY="mykey" -p 25225:25225 -p 25224:25224/udp  --restart-condition=on-failure microsoft/oms

it displays an error message: Error response from daemon: 404 page not found.
What is the reason for it ?

**Comment by keikhara** [comment]
@anushkaee can you provide details on steps you've taken? 
OMS requires WSID and KEY to be inserted. Have you add those when running docker run? 

thanks,

**Comment by anushkaee** [comment]
@keikhara 

 I did following steps,

1.	Provisioned the OMS using below link,
https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoft.containersoms

2.	Collected the WSID and Primary_key from OMS Portal  --> Settings --> Connected Sources 

3.	I followed below documentation to configure OMS with Azure Container service  (DockerSwarm).
               https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-containers
 
```
Then I tried to  run OMS agent in ACS swarm cluster  master node using below command:
 
command:  docker service create --name omsagent --mode global --mount type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock -e WSID="544bd26c-8ac1-4e65-b5bb-f475a03830a9" –e KEY="oMa3ASj16Jv9V+KZGdnfpicSwb3TkfI4GdpGe5i+EGWlpXF509x3vyIFyeZbUYbov5DQGvJaACmvTfgSis015w==" -p 25225:25225 -p 25224:25224/udp --restart-condition=on-failure microsoft/oms
 
```
it displays an error message: **

> Error response from daemon: 404 page not found

**.


Have I missed any step ? or what causing this issue ?

**Comment by dvohra** [comment]
The Swarm mode has to be initialized on the Azure "Swarm master".

**Comment by keikhara** [comment]
@anushkaee  Has this issue still resurfacing? If so, please reactive this issue.
