### ISSUE TITLE
Logs not making it up to Container Monitoring Solution

### ISSUE THREAD

**Issue by wandergeek** [Microsoft/OMS-docker#75]
Hello,

I'm having issues getting any of my logs to reach the _Container Logs_ section of Container Monitoring Solution. Im guessing this is because the agent is sending the logs using the ContainerLogs data type? I can see some logs coming thru on _syslog_ but all of the docker information is lost. 

I'm running the OpenLogic CentOS 7.3 image, and have selinux disabled. I am not doing any fancy orchestration, simply launching containers using the run command. I do see logs from my containers coming on standard out. Agent 1.4.0 is running locally alongside docker 1.12.6.  

Any help would be greatly appreciated!

Cheers,
Nick

**Comment by dizdeveloper** [comment]
Having the same issue not able to see container logs in OMS portal or log search. Please look into it.

**Comment by Stijnc** [comment]
@wandergeek and @dizdeveloper,

I had the issue as well and @keikhara pointed me to the [release notes](https://github.com/Microsoft/OMS-docker/blob/master/ReleaseNote.md#due-to-the-backend-changes-for-container-monitoring-with-oms-agent-for-linux-and-it-is-a-fresh-install-you-will-need-to-run-this-workaround) fresh install workaround.

re-onboarding the oms agent copied the container.conf file to /etc/opt/microsoft/omsagent/conf/omsagent.d/. a couple of minutes later all container info is available in Log Analytics.

Could you try this?

**Comment by ionutgrecu-adv365** [comment]
@Stijnc I'm running the OMS inside a pod/container. I can see logs under ContainerLog, ContainerServiceLog, ContainerInventory, ContainerImageInventory but not the KubeEvents_CL and KubePodInventory_CL

**Comment by keikhara** [comment]
Please try the latest agent and if there is any issues, please reach out again.
