### ISSUE TITLE
OMS Agent does not detect Kubernetes orchestrator

### ISSUE THREAD

**Issue by edevil** [Microsoft/OMS-docker#77]
I run the OMS Agent in all vms (masters and nodes) but the agent log shows that it doesn't detect that it is running inside Kubernetes:

```
instance of Container_HostInventory
{
    [Key] InstanceID=52b9541c-8123-481e-8b70-d31f2dc258af
    Computer=node-3-vm
    DockerVersion=1.12.6
    OperatingSystem=Container Linux by CoreOS 1465.8.0 (Ladybug)
    Volume=local
    Network=null host bridge overlay
    NodeRole=Not Orchestrated
    OrchestratorType=None
}
Primary Workspace: XXX    Status: Onboarded(OMSAgent Running)
omsagent 1.4.1.45
```

Is there some configuration variable for this?

**Comment by samisms** [comment]
Is this ACS ?

**Comment by edevil** [comment]
No, I have my own Kubernetes deployment script on Azure.

https://github.com/edevil/kubernetes-deployment

**Comment by edevil** [comment]
ping @keikhara

**Comment by keikhara** [comment]
@edevil We will have a new agent coming soon. Will let you know.

**Comment by edevil** [comment]
@keikhara Ok, that's good to know. But can you share with us how the agent will detect if it's running inside Kubernetes? Is it a configuration flag? Do I have to create the cluster machines with a specific name?

**Comment by vishiy** [comment]
@edevil Do you see any errors in /var/opt/microsoft/docker-cimprov/log/kubernetes_client_log.txt ?

**Comment by edevil** [comment]
@vishiy 
```
root@omsagent-88ks4:~# ls -l /var/opt/microsoft/docker-cimprov
total 8
drwxr-xr-x. 1 root root 4096 Feb  8 14:09 state
root@omsagent-88ks4:~#
```

**Comment by vishiy** [comment]
@edevil - Thanks! It looks like we look for  string 'k8' in computer name to detect it as k8s.
Thanks to @samisms . I will create a bug to do it in a more reliable way.

**Comment by edevil** [comment]
@vishiy I have tried creating a cluster with the names omsagent expects:

```
{
    [Key] InstanceID=bc7c754e-691e-4307-ac5d-0f08cbf3e2eb
    Computer=k8s-agent-0
    DockerVersion=17.09.1-ce
    OperatingSystem=Container Linux by CoreOS 1632.2.1 (Ladybug)
    Volume=local
    Network=bridge host macvlan null overlay
    NodeRole=Agent
    OrchestratorType=Kubernetes
}
```

However, I still see NO k8s related information reported in the OMS portal:

<img width="1045" alt="screen shot 2018-02-12 at 14 06 52" src="https://user-images.githubusercontent.com/12426/36100410-124695f6-0ffe-11e8-9a5c-26dd662153be.png">

I'm using version oms:1.4.3-174 of the OMS agent.

**Comment by cricketfan5** [comment]
@here Can someone help me with the below issue ?
I am installing the omsagent as a daemonset kubernetes hosts. I was able to install successfully with no error at the time of installation but it is not turning in green(green tick mark in the portal stating it is being monitored). And I see below error in the this path 

Error:Unsupported Operation system: COREOS 1632.2.1.
I am installing the  OMSagent version(1.6.0-42) on COREOS version VERSION=1576.5.0
VERSION_ID=1576.5.0
BUILD_ID=2018-01-05-1121
PRETTY_NAME="Container Linux by CoreOS 1576.5.0 (Ladybug)"
Any help is appreciated. Thanks in advance
