### ISSUE TITLE
OMS portal shows errors for doke

### ISSUE THREAD

**Issue by MoimHossain** [Microsoft/OMS-docker#81]
Hi I am trying to connect my swarm cluster with OMS, I followed the instruction and ran the swarm service (global) - but I receive error messages on OMS portal like following:

```
Failed to resolve entity 'DockerVersion_s'.
Failed to resolve entity 'Name_s'.
```

What's going wrong here?

**Comment by keikhara** [comment]
This should be fixed by now. If you still seeing this issue, please reactive this issue.
