### ISSUE TITLE
Bad Argument Error when deploying OMSAgent 

### ISSUE THREAD

**Issue by lmiroslaw** [Microsoft/OMS-docker#83]
When deploying OMS as described here:
https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-monitor

I get the following error:
{"error":{"message":"The request had some invalid properties","code":"BadArgumentError","innererror":{"code":"SyntaxError","message":"Syntax Error","information":{"details":"{\"error\":{\"code\":\"Bad request\",\"message\":\"Request is invalid and cannot be executed.\",\"innererror\":{\"code\":\"SEM0001\",\"message\":\"Failed to resolve entity 'KubePodInventory_CL'\",\"@context\":{\"activityId\":\"3949f942-5757-4176-89d5-1252ebbb0626\"},\"@errorCode\":\"SEM0001\",\"@errorMessage\":\"Failed to resolve entity 'KubePodInventory_CL'\"}}}"}}}}

Updating the omsagent to agentVersion: 1.4.1-45 did not help.

**Comment by keikhara** [comment]
@lmiroslaw  can you provide us more info this? We like to try to reproduce this.

**Comment by keikhara** [comment]
This has been fixed. If you see the issue again, please reactive this.
