### ISSUE TITLE
Errors in omsagent-ds-secrets.yaml

### ISSUE THREAD

**Issue by adhodgson1** [Microsoft/OMS-docker#91]
Hi,

Having trouble with deploying latest OMS agent to Kubernetes with omsagent-ds-secrets.yaml

Git commit: cd9103e415b0de4c278c47b3091a0a0d063f2da7 (HEAD -> master, origin/master, origin/HEAD)

First error:
C:\repo\oms-docker\Kubernetes>kubectl apply -f omsagent-ds-secrets.yaml
error: error converting YAML to JSON: yaml: line 31: found a tab character that violate indentation

Fixed that then ran the command again:

C:\repo\oms-docker\Kubernetes>kubectl apply -f omsagent-ds-secrets.yaml
The DaemonSet "omsagent" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"agentVersion":"1.4.3-174", "app":"omsagent", "dockerProviderVersion":"1.0.0-30"}: `selector` does not match template `labels`

Any chance this could be fixed?

Thanks.
Andrew.

**Comment by keikhara** [comment]
@adhodgson1 we did fix the yaml file for line 31. 

For the second piece, let us look into it.

**Comment by keikhara** [comment]
@adhodgson1  we will publish new yaml file to support apply.
