### ISSUE TITLE
Ignore logs from certain containers (kube-svc-redirect)

### ISSUE THREAD

**Issue by Hinton** [Microsoft/OMS-docker#92]
In Azure Container Service (AKS), the built in service `kube-svc-redirect` generates a huge amount of logs, more than 500k daily. Which fills up mos the free quota of Azure Log Analytics.

Since those logs are of no particular value to us, I would like a way to be able to specify that a specific container should not have their logs collected. Possibly using kubernetes annotations on `kube-svc-redirect` if possible.

**Comment by keikhara** [comment]
@Hinton thank you for the feedback. Let us put that to our backlog.

**Comment by leongyh** [comment]
There are a couple of additional AKS built in services that are also generating a lot of logs that we do not need.

- kube-svc-redirect
- hcp-tunnel-front
- hyperkube-amd64

As @Hinton suggested, perhaps a way to specify container names to collect logs from would be a great feature.

**Comment by nsimmonds** [comment]
+1 on this

Part of the issue is that the logs are multiline for no real reason. They aren't stacktraces, there's no additional value from multiple lines. They also aren't indented after the first, the way a stacktrace would be. Even worse, the body of the log starts and ends with the same series of symbols, several plus signs, so there's no ability to regex a starting and ending line.

**Comment by keikhara** [comment]
@Hinton Are you using using Azure Monitor - container health in AKS. 
https://docs.microsoft.com/en-us/azure/monitoring/monitoring-container-health 
We do not capture kube-system logs which includes kube-svc-redirect. Please try the container monitoring product.

**Comment by htuomola** [comment]
@keikhara we're using oms-agent (stable/msoms chart) on a Kubernetes cluster that was setup with acs-engine (not AKS) and the Container health solution with that. Is that something different to what you're referring to? I see a ton of logs from hyperkube-amd64, most of which provide little to no value. Some kind of config override to ignore logs would be great.
