### ISSUE TITLE
OC Commands is not updated

### ISSUE THREAD

**Issue by HatemAlSum** [Microsoft/OMS-docker#97]
odam command are no longer exists

**Comment by keikhara** [comment]
@HatemAlSum  let me test this and get this updated.

**Comment by HatemAlSum** [comment]
Waiting your feedback

**Comment by keikhara** [comment]
@HatemAlSum this works on 3.9. Once OpenShift deprecate the command, we will update it.

**Comment by HatemAlSum** [comment]
this issue occur with 3.6 version
